version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql_ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  metabase:
    image: metabase/metabase
    container_name: metabase_ecommerce
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data

  adminer:
    image: adminer
    container_name: adminer_ecommerce
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
  metabase_data:
